### ISSUE TITLE
Feature Request/Recommendation: Don't make objects for hidden terrain objects

### ISSUE THREAD

**Issue by Whitsel** [Seb105/Arma-Briefingtable#1]
Awesome work so far! From playing around with this for a couple of minutes it does not yet appear to be able to differentiate between hidden and nonhidden objects. It's a somewhat niche use case perhaps but sometimes I like to somewhat redesign an area and as of right now this mod would show both the old and the new building in one another.

Screenshot referencing an example. The thatch huts are hidden but still appear
https://i.gyazo.com/dfe1e6c20837c4b3954012b0c2515d96.png

https://community.bistudio.com/wiki/isObjectHidden

**Comment by Seb105** [comment]
Will implement in next release.
