### ISSUE TITLE
Feature Request / Make this into a script

### ISSUE THREAD

**Issue by martuksxxxx** [Seb105/Arma-Briefingtable#5]
Make this mod into a script which you can put into mission folder with sqf and stuff

**Comment by nodrog1061** [comment]
I'm pretty sure this doesn't need a Feature Request all you need to do is put [fn_clearTable.sqf](https://github.com/Seb105/Arma-Briefingtable/blob/ae4b56b5cac49ce7a6d629ae7b6a6d195b9eb561/addons/main/functions/fn_clearTable.sqf) and [fn_createTable.sqf](https://github.com/Seb105/Arma-Briefingtable/blob/ae4b56b5cac49ce7a6d629ae7b6a6d195b9eb561/addons/main/functions/fn_createTable.sqf) in your mission files functions folder then call the script using [execVM](https://community.bistudio.com/wiki/execVM) like you usually do as I don't think this mod uses any code or objects that are not in base Arma 3 so you should be able to simply call it. please correct me if I'm wrong.

**Comment by Seb105** [comment]
fn_createTable uses defined function calls (it calls clearTable internally). This'll cause errors just execVMing it, but you can just use cfgFunctions in description.ext to add them.

I'm going to create a standalone version that doesn't require the mod eventually.

**Comment by Seb105** [comment]
Duplicate of https://github.com/Seb105/Arma-Briefingtable/issues/9
