### ISSUE TITLE
BUG - On some tables map is underground

### ISSUE THREAD

**Issue by nodrog1061** [Seb105/Arma-Briefingtable#7]
On some tables, the map appears under the table my suggestion is either you add the ability to offset the map horizontally from the call or add a set of saved hights for objects or get the plane top plane of the desk using defined planes in the objects .p3d file 

![image](https://user-images.githubusercontent.com/59317189/111037771-8aa63b00-841d-11eb-9ba2-203fbb89a03a.png)
![image](https://user-images.githubusercontent.com/59317189/111037786-a0b3fb80-841d-11eb-8021-329237ce007a.png)

the desk has a defined surface called "screenlarge" used for textures you could use this.
![image](https://user-images.githubusercontent.com/59317189/111038008-9e05d600-841e-11eb-8ed5-524786267732.png)

however, comping tables don't have this defined so instead you could use the "roadway" or the "geometry" to get the raw hight of the object
![image](https://user-images.githubusercontent.com/59317189/111038137-42881800-841f-11eb-8e02-a149820a0b2f.png)
![image](https://user-images.githubusercontent.com/59317189/111038153-5a5f9c00-841f-11eb-92d9-6fe089537e7d.png)

**Comment by Seb105** [comment]
Fix might be as simple as changing the LOD used for the height check. What is the classname of that table?
